<a href="https://colab.research.google.com/github/Andrii-Oliinyk-2726/Data_Science_HW1/blob/main/Data_Science_HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# 1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.
import numpy as np
nat_numbers = np.arange(1, 11)
print(nat_numbers)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
# 2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
matrix = np.zeros((3, 3), dtype="u1")
print(matrix)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [23]:
# 3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
matrix = np.random.randint(1, 11, size=(5, 5))
print(matrix)

[[ 3  9  5 10 10]
 [ 4  3  9  5  7]
 [10  4  8 10  2]
 [ 1  7  8  7  6]
 [10  4  1  8  4]]


In [25]:
# 4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.
matrix = np.random.random((4, 4))
print(matrix)

[[0.22753548 0.30524366 0.0229801  0.21437795]
 [0.44863209 0.75028153 0.82798864 0.98038211]
 [0.94088921 0.45237811 0.50748127 0.23593545]
 [0.45545256 0.89771435 0.83326799 0.51625884]]


In [38]:
# 5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10
#    та виконайте на них поелементні операції додавання, віднімання та множення.
a = np.random.randint(1, 11, size=5)
b = np.random.randint(1, 11, size=5)
print('a:             ', a)
print('b:             ', b)
print('Add:           ', a+b)
print('Subtraction:   ', a-b)
print('Mltiplication: ', a*b)

a:              [ 5  1  7  1 10]
b:              [ 1  4  1  5 10]
Add:            [ 6  5  8  6 20]
Subtraction:    [ 4 -3  6 -4  0]
Mltiplication:  [  5   4   7   5 100]


In [46]:
# 6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.
a = np.random.random(7)
b = np.random.random(7)
print('a: ', a)
print('b: ', b)
print('Scalar product: ', np.dot(a, b))


a:  [0.68065995 0.71286327 0.61605498 0.51826153 0.53087657 0.35347035
 0.43292775]
b:  [0.41491016 0.50433667 0.89602046 0.83859181 0.6378724  0.95390019
 0.40226597]
Scalar product:  2.478502602481039


In [2]:
# 7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 3))

print(a)
print(b)
print(np.dot(a, b))

[[ 2  8]
 [ 1 10]]
[[3 6 3]
 [7 2 9]]
[[62 28 78]
 [73 26 93]]


In [10]:
# 8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.
a = np.random.randint(1, 11, size=(3, 3))
print(a)
a_inv = np.linalg.inv(a)
print(a_inv)

[[7 8 8]
 [7 9 4]
 [7 5 9]]
[[-0.79220779  0.41558442  0.51948052]
 [ 0.45454545 -0.09090909 -0.36363636]
 [ 0.36363636 -0.27272727 -0.09090909]]


In [11]:
# 9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.
a = np.random.random((4, 4))
b = a.T
print(a)
print(b)

[[0.70648268 0.16390203 0.58524576 0.2565849 ]
 [0.51738814 0.94328198 0.12454916 0.43898089]
 [0.7749961  0.26528024 0.39398733 0.53471558]
 [0.82516655 0.23909698 0.73338307 0.29651918]]
[[0.70648268 0.51738814 0.7749961  0.82516655]
 [0.16390203 0.94328198 0.26528024 0.23909698]
 [0.58524576 0.12454916 0.39398733 0.73338307]
 [0.2565849  0.43898089 0.53471558 0.29651918]]


In [19]:
# 10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.
matrix = np.random.randint(1, 11, size=(3, 4))
v = np.random.randint(1, 11, size=4)
print(matrix)
print(v)
print(np.dot(matrix, v))

[[ 9  4  4 10]
 [ 9  4 10  4]
 [ 1 10  4  3]]
[8 7 5 6]
[180 174 116]


In [18]:
# 11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.
matrix = np.random.random((2, 3))
v = np.random.random(3)
print(matrix)
print(v)
print(np.dot(matrix, v))

[[0.43521234 0.96244293 0.78489666]
 [0.78269063 0.55063823 0.07686865]]
[0.29497372 0.76866318 0.65247297]
[1.3802945  0.70428321]


In [21]:
# 12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.
matrix_1 = np.random.randint(1, 11, size=(2, 2))
matrix_2 = np.random.randint(1, 11, size=(2, 2))
print(matrix_1)
print(matrix_2)
print(matrix_1 * matrix_2)

[[5 8]
 [4 4]]
[[2 5]
 [3 8]]
[[10 40]
 [12 32]]


In [22]:
# 13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.
matrix_1 = np.random.randint(1, 11, size=(2, 2))
matrix_2 = np.random.randint(1, 11, size=(2, 2))
print(matrix_1)
print(matrix_2)
print(np.dot(matrix_1, matrix_2))

[[ 3  5]
 [10  9]]
[[7 6]
 [5 6]]
[[ 46  48]
 [115 114]]


In [30]:
# 14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.
matrix = np.random.randint(1, 101, size=(5, 5))
print(matrix)
print(matrix.sum())

[[37 59 25 97 48]
 [36 11 63 29 60]
 [37 61 15 57 56]
 [45 67 55 45 62]
 [64 98 65  3 96]]
1291


In [33]:
# 15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.
matrix_1 = np.random.randint(1, 11, size=(4, 4))
matrix_2 = np.random.randint(1, 11, size=(4, 4))
print(matrix_1)
print(matrix_2)
print(matrix_1 - matrix_2)

[[3 8 6 8]
 [4 5 7 6]
 [1 5 6 4]
 [2 6 8 6]]
[[ 1  1  3  1]
 [ 1  7  8 10]
 [10  2  1  3]
 [ 4  8  1  2]]
[[ 2  7  3  7]
 [ 3 -2 -1 -4]
 [-9  3  5  1]
 [-2 -2  7  4]]


In [41]:
# 16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.
matrix = np.random.random((3, 3))
row_sums = np.sum(matrix, axis=1)
column_vector = row_sums.reshape(-1, 1)
print(matrix)
# print(row_sums)
print(column_vector)

[[0.76931318 0.13227394 0.98033823]
 [0.77978803 0.04228303 0.63802686]
 [0.30731956 0.97775712 0.61886288]]
[[1.88192535]
 [1.46009792]
 [1.90393956]]


In [46]:
# 17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.
matrix = np.random.randint(1, 11, size=(3, 4))
squared_matrix = np.square(matrix)
print(matrix)
print(squared_matrix)

[[ 9  9 10  4]
 [ 8  8  9  8]
 [ 8  6  1  6]]
[[ 81  81 100  16]
 [ 64  64  81  64]
 [ 64  36   1  36]]


In [51]:
# 18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.
v = np.random.randint(1, 51, size=4)
sqrt_v = np.sqrt(v)
print(v)
print(sqrt_v)

[ 7  6  1 28]
[2.64575131 2.44948974 1.         5.29150262]
